<template>
  <div class="policy">
    <TopPage :currentPage="'Returns Policy'" />

    <div class="policy-content">
      <div class="grid wide">
        <div class="policy-wrap">
          <p class="policy-heading">Return &amp; Refund Policy</p>
          <p class="policy-para">
            Our Return and Refund Policy was last updated at
            <span class="highlight">03 July, 2022</span>
            <br />
            Thank you for shopping at <span class="highlight">Organia</span>
            <br />
            If, for any reason, You are not completely satisfied with a purchase
            We invite You to review our policy on refunds and returns. This
            Return and Refund Policy was generated by TermsFeed Return and
            Refund Policy Generator.
            <br />
            The following terms are applicable for any products that You
            purchased with Us.
          </p>
        </div>
        <div class="policy-wrap">
          <p class="policy-heading">Interpretation</p>
          <p class="policy-para">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
        </div>
        <div class="policy-wrap">
          <p class="policy-heading">Definitions</p>
          <p class="policy-para">
            For the purposes of this Return and Refund Policy:
          </p>
          <ul>
            <li>
              "Company" &lpar;referred to as either "the Company", "We", "Us" or
              "Our" in this Agreement&rpar; refers to DragonDev Company.
            </li>
            <li>
              "Goods" refers to the items offered for sale on the Service.
            </li>
            <li>"Orders" means a request by You to purchase Goods from Us.</li>
            <li>"Service" refers to the Website.</li>
            <li>
              "Website" refers to Organia, accessible from
              <span class="highlight">https://organia.com</span>
            </li>
            <li>
              "You" means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </li>
          </ul>
        </div>
        <div class="policy-wrap">
          <p class="policy-heading">Your Order Cancellation Rights</p>
          <p class="policy-para">
            You are entitled to cancel Your Order within 14 days without giving
            any reason for doing so.
            <br />
            The deadline for cancelling an Order is 14 days from the date on
            which You received the Goods or on which a third party you have
            appointed, who is not the carrier, takes possession of the product
            delivered.
            <br />
            We will reimburse You no later than 14 days from the day on which We
            receive the returned Goods. We will use the same means of payment as
            You used for the Order, and You will not incur any fees for such
            reimbursement.
          </p>
        </div>
        <div class="policy-wrap">
          <p class="policy-heading">Conditions for Returns</p>
          <p class="policy-para">
            In order for the Goods to be eligible for a return, please make sure
            that:
          </p>
          <ul>
            <li>The Goods were purchased in the last 14 days</li>
            <li>The Goods are in the original packaging</li>
          </ul>
          <p class="policy-para">
            We reserve the right to refuse returns of any merchandise that does
            not meet the above return conditions in our sole discretion.
          </p>
        </div>
        <div class="policy-wrap">
          <p class="policy-heading">Contact Us</p>
          <p class="policy-para">
            If you have any questions about our Returns and Refunds Policy,
            please contact us:
          </p>
          <ul>
            <li>
              By visiting this page on our website:
              <span class="highlight">https://organia.com</span>
            </li>
            <li>
              By sending us an email:
              <span class="highlight">thanhlongedu0304@gmail.com</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
/* eslint-disable */
import TopPage from "@/components/TopPage.vue";

export default {
  name: "PolicyPage",
  components: {
    TopPage,
  },
};
</script>

<style lang="scss" scoped>
@use "@/assets/scss/variables.scss" as *;

.policy {
  &-content {
    padding: 100px 0 60px;
    background: url("@/assets/images/home/bodybg.png") no-repeat left center
      $bodyColor;
  }

  &-wrap {
    margin-bottom: 42px;

    &:last-child {
      margin-bottom: 0;
    }
  }

  &-heading {
    color: $primaryColor;
    font-size: 30px;
    margin-bottom: 15px;
    font-weight: bold;
    line-height: 1.2;
  }

  &-para {
    font-size: 20px;
    line-height: 1.4;
    color: #252525;
  }

  ul {
    padding: 8px 0 8px 24px;
  }

  li {
    font-size: 20px;
    line-height: 1.4;
    color: #252525;
    position: relative;

    &::before {
      content: "•";
      color: inherit;
      position: absolute;
      top: 0;
      left: -16px;
    }
  }

  li + li {
    margin-top: 12px;
  }

  .highlight {
    color: $primaryColor;
    font-weight: 500;
  }

  @media (max-width: $maxMobile) {
    &-content {
      padding: 65px 0 30px;
    }

    &-heading {
      font-size: 24px;
    }

    &-para,
    li {
      font-size: 18px;
    }
  }
}
</style>
